services:
  - type: web
    name: broker-plus-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: broker-plus-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

databases:
  - name: broker-plus-db
    databaseName: brokerplus
    user: brokerplus
    plan: free